version: '3.3'
services:

  backend:
    build: ./backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./backend:/usr/src/app"
      - "./data/leveldb:/var/lib/leveldb/data"
      - "./data/logs/backend:/usr/src/app/app/logs"
      - "./data/ethernode/geth_ipc:/usr/src/geth_ipc:ro"
    environment:
      NODE_ENV: development
      PRODUCTION_MODE: "OFF"
      PLASMA_CONTRACT_ADDRESS: '0xb676958593081566f4977e2644F86e10439A4869'
      PLASMA_OPERATOR_ADDRESS: '0x11A618DE3ADe9B85Cd811BF45af03bAd481842Ed'
      PLASMA_OPERATOR_PRIVATE: ''
      PLASMA_OPERATOR_PASSWORD: ''
    command: 'npm run development'
    logging:
      options:
        max-size: 1000m
    restart: 'no'
